"""Export the public static Application Tracker dashboard demo.

The deployed demo must use the same dashboard renderer as the local tracker.
It differs only in payload source and write surface:

- local mode reads private SQLite data and may show Raw intake;
- public demo mode reads application-tracker/demo_payload.json;
- public demo mode strips the Raw intake form before writing the static HTML.
"""

from __future__ import annotations

import json
from pathlib import Path

import acb_tracker
import acb_tracker_readonly


TRACKER_ROOT = Path(__file__).resolve().parent
REPO_ROOT = TRACKER_ROOT.parent
DEMO_PAYLOAD = TRACKER_ROOT / "demo_payload.json"
DEFAULT_OUTPUT = REPO_ROOT / "site" / "application-tracker" / "index.html"


def export_demo_dashboard(output: Path = DEFAULT_OUTPUT) -> Path:
    payload = json.loads(DEMO_PAYLOAD.read_text(encoding="utf-8"))
    html = acb_tracker.dashboard_html(payload)
    html = acb_tracker_readonly.INTAKE_SECTION_PATTERN.sub("", html)
    banner = "<!-- Generated by application-tracker/export_demo_dashboard.py from application-tracker/demo_payload.json. Do not hand-edit. -->\n"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(banner + html, encoding="utf-8", newline="\n")
    return output


def main() -> int:
    output = export_demo_dashboard()
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
